/*
 * Automatically generated C config: don't edit
 * Dist builder
 * Mon Jun 19 08:57:48 2017
 */
#ifndef _AUTOCONF_H_
#define _AUTOCONF_H_
#define AUTOCONF_INCLUDED
#define CONFIG_ROMNAME "68EPSPIFA.bin"
#define CONFIG_CHIPSET 1
#define CONFIG_USB_BULK_TEST 1
#define CONFIG_SMBIOS_ENABLED 1
#define CONFIG_SMBIOS_RTK 1
#define CONFIG_PRODUCT "dash"
#define CONFIG_VERSION 15
#define CONFIG_VENDOR_GENERIC 1
#define CONFIG_KCS_ENABLED 1
#define CONFIG_BIOS 0
#define CONFIG_SMBUSLOG_DEBUG 1
#define CONFIG_UDP_ENABLED 1
#define CONFIG_OTG_ENABLED 1
#define CONFIG_USB_ENABLED 1
#define CONFIG_SSH_ENABLED 1
#define CONFIG_CHIPSET_AMD 1
#define CONFIG_REALTEK_WEB_UI 1
#define CONFIG_BLOCK_WRITE 1
#define CONFIG_DISTVERSION "1.0.0"
#define CONFIG_BIOS_AMI 1
#define CONFIG_DEBUG 1
#define CONFIG_DHCP_ENABLED 1
#define CONFIG_DASH_ENABLED 1
#define CONFIG_PLDMTYPE 1
#define CONFIG_BIOSTYPE 1
#define CONFIG_ENABLED_DEFAULT_PEC 1
#define CONFIG_HTTP_ENABLED 1
//#define CONFIG_USBLOG_DEBUG 0
#define CONFIG_REMOTE_DEBUG 1
#define CONFIG_CODEC_ENABLED 1
#define CONFIG_USB_DEBUG 1
#define CONFIG_UEFI_BIOS 1
#define CONFIG_USB_FLASH 1
#define CONFIG_VENDOR 3
#define CONFIG_IC_VERSION_FP_RevA 1
#define CONFIG_PLDM_MULTI_TRANSFER 1
#endif/* _AUTOCONF_H_*/
